from pptx.util import Inches


STANDARD_WIDESCREEN_NAME = "PowerPoint Widescreen (16:9)"
SLIDE_WIDTH_INCHES = 13.333
SLIDE_HEIGHT_INCHES = 7.5
MARP_SIZE = "16:9"

SLIDE_WIDTH = Inches(SLIDE_WIDTH_INCHES)
SLIDE_HEIGHT = Inches(SLIDE_HEIGHT_INCHES)
